### ISSUE TITLE
faster despace64

### ISSUE THREAD

**Issue by aqrit** [lemire/despacer#2]
parts of HASZERO/HASVALUE can be eliminated if not matching signed bytes
other parts can be deferred & combined when checking multiple values

https://gist.github.com/aqrit/6e73ca6ff52f72a2b121d584745f89f3

other things of interest in that gist (speeds unknown)
* swar method for removing bytes from a word 
* sse2 using prefix sums and lots of shifting
* ssse3 using 1024 byte lut

**Comment by lemire** [comment]
Thanks. I'll review.

**Comment by aqrit** [comment]
wow, nevermind...
http://0x80.pl/articles/mask-zero-nonzero-bytes.html

**Comment by aqrit** [comment]
I fixed my SWAR function, for a cost of two extra operations.

however, despace64 can still use the previous modified HASZERO method and benefit by removing a couple bitwise nots
```
       // set sign-bit if potential match byte
	size_t mask =
			((asrc ^ mask_09) - mask_01) | 
			((asrc ^ mask_0A) - mask_01) | 
			((asrc ^ mask_0D) - mask_01) |
			((asrc ^ mask_20) - mask_01);
	mask &= ~asrc; // don't match if src byte is signed
	mask &= mask_80; // zero garbage bits

	if( mask != 0){
		for (int k = 0; k < 8; k++) {
			char c = bytes[i + k];
			if (c == '\r' || c == '\n' || c == ' ' || c == '\t' ) { // check each byte in-case of misfire
			  continue;
			}
			bytes[pos++] = c;
		}
	}
```

**Comment by lemire** [comment]
Thanks. Back on my todo list. ;-)

**Comment by lemire** [comment]
Any chance you might turn this issue into a pull request?

**Comment by aqrit** [comment]
I've added two `despace_block_64` examples to the gist

> Any chance you might turn this issue into a pull request?
at some point I'll send one over with everything in it.

**Comment by lemire** [comment]
+1

**Comment by aqrit** [comment]
I'll leave my changes as a fork for now.
Still have some tinkering to do.
